### ISSUE TITLE
Host ureachable

### ISSUE THREAD

**Issue by lpsayo** [mkheck/planefinder#1]
Hi Mark, I downloaded the source code, compiled, run (simply mvn spring-boot:run)  and got this error, IO Exception: No route to host (Host unreachable), generating and providing sample data.

It's been like that for a couple of days now. Is there a way around this or an alternative site?

**Comment by mkheck** [comment]
Thanks for checking it out! That's actually expected behavior: if you can't reach my personal PlaneFinder.net device that receives local air traffic data and shares it via a REST API (here behind my firewall), the PlaneFinder Spring Boot app produces an exception in the log while generating some sample data for use in all of the examples.

If you'd like to receive live flight data for your area, it's possible to either request a device from the folks at PlaneFinder (if they still need coverage where you reside) or create one using a Raspberry Pi and a Raspbian/software build. But all examples in the book work perfectly well with the sample data generated by the PlaneFinder app in the repo, so it's entirely optional.

Hope this helps, and again, thank you for digging into the book and code!
